from __future__ import annotations

import json
import logging
import re
from typing import Any, Dict, List, Optional

from app.models.task import RiskLevel, StepStatus, TaskConstraints, TaskStep
from app.services.openrouter import ModelQuality, openrouter_client
from app.services.skill_router import SkillDomain, SkillPersona, get_persona

logger = logging.getLogger(__name__)


class PlannerService:
    """
    Generate structured task plans using skill-aware prompting.

    Drawing from:
      - obra/superpowers: writing-plans (atomic, verifiable steps)
      - alirezarezvani: domain-specific planning personas
      - trailofbits: ask-questions-if-underspecified (detect vague goals)
      - levnikolaevich: ln-200-scope-decomposer (numbered pipeline)
    """

    async def create_plan(
        self,
        goal: str,
        constraints: TaskConstraints,
        context: Optional[str] = None,
    ) -> List[TaskStep]:
        persona = get_persona(goal)
        logger.info("Planner: using persona '%s' for goal: %s", persona.domain.value, goal[:80])

        user_message = self._build_prompt(goal, constraints, context, persona)
        messages = [
            {"role": "system", "content": persona.planner_system + "\n\n" + _PLAN_FORMAT_INSTRUCTIONS},
            {"role": "user", "content": user_message},
        ]

        try:
            text, model, cost = await openrouter_client.chat_completion(
                messages=messages,
                task_type="planning",
                quality=ModelQuality.FREE,
                max_tokens=2048,
            )
            logger.info("Plan generated by %s (cost=$%.6f)", model, cost)
            steps = self._parse_plan(text, persona)
            return self._apply_constraints(steps, constraints)
        except Exception as exc:
            logger.error("PlannerService.create_plan failed: %s", exc)
            return self._fallback_plan(goal, persona)

    async def replan(
        self,
        goal: str,
        completed_steps: List[TaskStep],
        failed_step: TaskStep,
        error: str,
        constraints: TaskConstraints,
    ) -> List[TaskStep]:
        persona = get_persona(goal)
        completed_summary = "\n".join(
            f"- {s.description} [DONE]" for s in completed_steps
        )
        user_message = (
            f"Original goal: {goal}\n\n"
            f"Completed steps:\n{completed_summary}\n\n"
            f"Failed step: {failed_step.description}\n"
            f"Error: {error}\n\n"
            "Generate a revised plan (JSON array) for the remaining work. "
            "Avoid repeating the failed approach. "
            "Completed steps do NOT need to be replanned."
        )

        messages = [
            {"role": "system", "content": persona.planner_system + "\n\n" + _PLAN_FORMAT_INSTRUCTIONS},
            {"role": "user", "content": user_message},
        ]

        try:
            text, model, cost = await openrouter_client.chat_completion(
                messages=messages,
                task_type="planning",
                quality=ModelQuality.FREE,
                max_tokens=1024,
            )
            new_steps = self._parse_plan(text, persona)
            return self._apply_constraints(new_steps, constraints)
        except Exception as exc:
            logger.error("PlannerService.replan failed: %s", exc)
            return []

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _build_prompt(
        self,
        goal: str,
        constraints: TaskConstraints,
        context: Optional[str],
        persona: SkillPersona,
    ) -> str:
        disabled: List[str] = []
        if not constraints.allowWeb:
            disabled.extend(["web_search", "hyperbrowser", "web_researcher"])
        if not constraints.allowFileSystem:
            disabled.append("filesystem")
        if not constraints.allowCodeExecution:
            disabled.append("code_executor")

        # Preferred tools for this domain
        preferred_str = ", ".join(persona.preferred_tools[:4])

        parts = [f"Goal: {goal}"]

        if persona.domain != SkillDomain.GENERAL:
            parts.append(
                f"\nDomain: {persona.domain.value.upper()}. "
                f"Preferred tools for this domain: {preferred_str}"
            )

        if disabled:
            parts.append(
                f"\nConstraints: These tools are NOT available: {', '.join(disabled)}"
            )

        if constraints.budget_usd < 0.10:
            parts.append(
                f"\nBudget: Only ${constraints.budget_usd:.2f} — use free models and minimal steps."
            )

        if context:
            parts.append(f"\nAdditional context:\n{context}")

        parts.append(
            "\nQuality criteria for this task:\n"
            + "\n".join(f"  - {c}" for c in persona.quality_criteria)
        )

        parts.append("\nCreate the plan:")
        return "\n".join(parts)

    def _parse_plan(self, text: str, persona: SkillPersona) -> List[TaskStep]:
        text = text.strip()
        if "```" in text:
            match = re.search(r"```(?:json)?\s*([\s\S]*?)```", text)
            if match:
                text = match.group(1).strip()

        start = text.find("[")
        end = text.rfind("]")
        if start == -1 or end == -1:
            logger.warning("No JSON array found in planner output: %s", text[:200])
            return []

        try:
            items: List[Dict[str, Any]] = json.loads(text[start : end + 1])
        except json.JSONDecodeError as exc:
            logger.warning("JSON parse error in planner output: %s", exc)
            return []

        steps: List[TaskStep] = []
        for item in items[:7]:
            if not isinstance(item, dict):
                continue
            tool = item.get("tool_to_use") or item.get("tool") or None

            # If domain is writing and tool is llm_only, upgrade to content_writer
            if (
                persona.domain == SkillDomain.WRITING
                and tool in ("llm_only", None, "")
                and any(
                    kw in str(item.get("description", "")).lower()
                    for kw in ("write", "draft", "compose", "chapter", "section", "guide", "ebook")
                )
            ):
                tool = "content_writer"

            # If tool is generic search on a research-heavy domain, upgrade to web_researcher
            if (
                persona.domain in (SkillDomain.RESEARCH, SkillDomain.WRITING)
                and tool == "web_search"
            ):
                tool = "web_researcher"

            step = TaskStep(
                description=str(item.get("description", "Unnamed step")),
                tool_used=tool,
                requires_approval=bool(item.get("requires_approval", False)),
            )
            steps.append(step)

        return steps

    def _apply_constraints(
        self, steps: List[TaskStep], constraints: TaskConstraints
    ) -> List[TaskStep]:
        _web_tools = {"web_search", "hyperbrowser", "web_researcher", "enhanced_search", "image_generator"}
        allowed: List[TaskStep] = []
        for step in steps:
            tool = step.tool_used
            if tool in _web_tools and not constraints.allowWeb:
                logger.info("Removing step (web not allowed): %s", step.description)
                continue
            if tool == "filesystem" and not constraints.allowFileSystem:
                logger.info("Removing step (fs not allowed): %s", step.description)
                continue
            if tool == "code_executor" and not constraints.allowCodeExecution:
                logger.info("Removing step (code not allowed): %s", step.description)
                continue
            allowed.append(step)
        return allowed

    def _fallback_plan(self, goal: str, persona: SkillPersona) -> List[TaskStep]:
        """Domain-aware fallback plan when LLM planner fails."""
        if persona.domain == SkillDomain.WRITING:
            return [
                TaskStep(description=f"Research background information for: {goal}", tool_used="web_researcher"),
                TaskStep(description=f"Write the complete content for: {goal}", tool_used="content_writer"),
                TaskStep(description="Review, polish and deliver the final document", tool_used="llm_only"),
            ]
        if persona.domain == SkillDomain.CODING:
            return [
                TaskStep(description=f"Design the architecture and data structures for: {goal}", tool_used="llm_only"),
                TaskStep(description="Implement the core logic", tool_used="code_executor"),
                TaskStep(description="Write tests and deliver working code", tool_used="llm_only"),
            ]
        if persona.domain == SkillDomain.RESEARCH:
            return [
                TaskStep(description=f"Conduct deep research on: {goal}", tool_used="web_researcher"),
                TaskStep(description="Synthesize findings into a structured research brief", tool_used="llm_only"),
            ]
        return [
            TaskStep(description=f"Research and gather information to address: {goal}", tool_used="web_search"),
            TaskStep(description="Synthesize findings and deliver final answer", tool_used="llm_only"),
        ]


# Shared format instructions appended to every planner system prompt
_PLAN_FORMAT_INSTRUCTIONS = """
Return ONLY a valid JSON array. Each element must have exactly these fields:
- description: string (what to do — be specific and verifiable)
- tool_to_use: string (one of: content_writer, web_researcher, enhanced_search, web_search, filesystem, code_executor, json_generator, hyperbrowser, image_generator, location, hf_inference, llm_only)
- expected_output: string (what success looks like — specific and measurable)
- requires_approval: boolean

Tool selection guide:
- content_writer: writing ebook chapters, articles, guides, reports — any substantial writing
- web_researcher: deep research tasks needing multiple sources and synthesis
- enhanced_search: quick fact lookups, current events, finding specific pages (uses SerpAPI + DDG)
- web_search: basic web search (use enhanced_search for better results)
- image_generator: create images or short videos from text prompts (WaveSpeed AI / Flux models)
- location: geocoding, places search, directions, distance matrix (Google Maps)
- hf_inference: run open-source AI models — text generation, classification, summarization
- code_executor: running or testing code
- filesystem: reading/writing files
- llm_only: reasoning, analysis, synthesis that doesn't need external tools

Example:
[
  {
    "description": "Research the OpenClaw tool: what it does, installation methods, key configuration options",
    "tool_to_use": "web_researcher",
    "expected_output": "Comprehensive research brief covering install steps, config options, and best practices",
    "requires_approval": false
  },
  {
    "description": "Write Chapter 1: Introduction to OpenClaw — what it is, why it matters, who should use it",
    "tool_to_use": "content_writer",
    "expected_output": "Complete 1200+ word chapter with engaging intro, clear explanation, and reader benefits",
    "requires_approval": false
  }
]"""


# Singleton
planner_service = PlannerService()
