from __future__ import annotations

import json
import logging
import re
from typing import Any, Dict, List, Optional

from app.models.task import RiskLevel, StepStatus, TaskConstraints, TaskStep
from app.services.openrouter import ModelQuality, openrouter_client

logger = logging.getLogger(__name__)

PLANNER_SYSTEM_PROMPT = """You are an expert AI task planner. Your job is to break down a user's goal into a concrete, ordered list of 3-7 actionable steps.

Available tools:
- filesystem: read/write/list files (sandboxed)
- web_search: search the web via DuckDuckGo
- hyperbrowser: scrape/browse web pages and extract structured data
- code_executor: run Python code (sandboxed, with approval)
- json_generator: structure data into JSON/CSV

Rules:
1. Each step must be atomic and verifiable.
2. Use the most appropriate tool for each step.
3. Mark steps that write files, run code, or delete data as requires_approval=true.
4. The last step should always synthesize and deliver the final answer.
5. Be specific about what each step does and what output is expected.

Return ONLY a valid JSON array. Each element must have these exact fields:
- description: string (what to do)
- tool_to_use: string (one of: filesystem, web_search, hyperbrowser, code_executor, json_generator, llm_only)
- expected_output: string (what success looks like)
- requires_approval: boolean

Example:
[
  {
    "description": "Search for recent news about topic X",
    "tool_to_use": "web_search",
    "expected_output": "List of 5 recent articles with titles and URLs",
    "requires_approval": false
  }
]"""


class PlannerService:
    """Generate structured task plans using OpenRouter."""

    async def create_plan(
        self,
        goal: str,
        constraints: TaskConstraints,
        context: Optional[str] = None,
    ) -> List[TaskStep]:
        """
        Generate a step-by-step plan for the given goal.

        Returns a list of TaskStep objects.
        """
        user_message = self._build_prompt(goal, constraints, context)

        messages = [
            {"role": "system", "content": PLANNER_SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ]

        try:
            text, model, cost = await openrouter_client.chat_completion(
                messages=messages,
                task_type="planning",
                quality=ModelQuality.FREE,
                max_tokens=2048,
            )
            logger.info("Plan generated by %s (cost=$%.6f)", model, cost)
            steps = self._parse_plan(text)
            return self._apply_constraints(steps, constraints)
        except Exception as exc:
            logger.error("PlannerService.create_plan failed: %s", exc)
            return self._fallback_plan(goal)

    async def replan(
        self,
        goal: str,
        completed_steps: List[TaskStep],
        failed_step: TaskStep,
        error: str,
        constraints: TaskConstraints,
    ) -> List[TaskStep]:
        """Generate a revised plan after a step failure."""
        completed_summary = "\n".join(
            f"- {s.description} [DONE]" for s in completed_steps
        )
        user_message = (
            f"Original goal: {goal}\n\n"
            f"Completed steps:\n{completed_summary}\n\n"
            f"Failed step: {failed_step.description}\n"
            f"Error: {error}\n\n"
            "Generate a revised plan (JSON array) for the remaining work. "
            "Avoid repeating the failed approach. "
            "Completed steps do NOT need to be replanned."
        )

        messages = [
            {"role": "system", "content": PLANNER_SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ]

        try:
            text, model, cost = await openrouter_client.chat_completion(
                messages=messages,
                task_type="planning",
                quality=ModelQuality.FREE,
                max_tokens=1024,
            )
            new_steps = self._parse_plan(text)
            return self._apply_constraints(new_steps, constraints)
        except Exception as exc:
            logger.error("PlannerService.replan failed: %s", exc)
            return []

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _build_prompt(
        self,
        goal: str,
        constraints: TaskConstraints,
        context: Optional[str],
    ) -> str:
        disabled: List[str] = []
        if not constraints.allowWeb:
            disabled.extend(["web_search", "hyperbrowser"])
        if not constraints.allowFileSystem:
            disabled.append("filesystem")
        if not constraints.allowCodeExecution:
            disabled.append("code_executor")

        constraint_note = ""
        if disabled:
            constraint_note = (
                f"\n\nConstraints: The following tools are NOT allowed: "
                f"{', '.join(disabled)}. Do not use them in any step."
            )
        if constraints.budget_usd < 0.10:
            constraint_note += (
                f"\n\nBudget: Only ${constraints.budget_usd:.2f} available. "
                "Use free models and minimal steps."
            )

        ctx_note = f"\n\nAdditional context:\n{context}" if context else ""
        return f"Goal: {goal}{constraint_note}{ctx_note}\n\nCreate a plan:"

    def _parse_plan(self, text: str) -> List[TaskStep]:
        """Extract JSON array from LLM output and convert to TaskStep list."""
        # Strip markdown fences
        text = text.strip()
        if "```" in text:
            match = re.search(r"```(?:json)?\s*([\s\S]*?)```", text)
            if match:
                text = match.group(1).strip()

        # Find JSON array
        start = text.find("[")
        end = text.rfind("]")
        if start == -1 or end == -1:
            logger.warning("No JSON array found in planner output: %s", text[:200])
            return []

        raw_json = text[start : end + 1]
        try:
            items: List[Dict[str, Any]] = json.loads(raw_json)
        except json.JSONDecodeError as exc:
            logger.warning("JSON parse error in planner output: %s", exc)
            return []

        steps: List[TaskStep] = []
        for item in items[:7]:  # max 7 steps
            if not isinstance(item, dict):
                continue
            step = TaskStep(
                description=str(item.get("description", "Unnamed step")),
                tool_used=item.get("tool_to_use") or None,
                requires_approval=bool(item.get("requires_approval", False)),
            )
            steps.append(step)

        return steps

    def _apply_constraints(
        self, steps: List[TaskStep], constraints: TaskConstraints
    ) -> List[TaskStep]:
        """Remove steps that violate constraints."""
        allowed: List[TaskStep] = []
        for step in steps:
            tool = step.tool_used
            if tool in ("web_search", "hyperbrowser") and not constraints.allowWeb:
                logger.info("Removing step (web not allowed): %s", step.description)
                continue
            if tool == "filesystem" and not constraints.allowFileSystem:
                logger.info("Removing step (fs not allowed): %s", step.description)
                continue
            if tool == "code_executor" and not constraints.allowCodeExecution:
                logger.info("Removing step (code not allowed): %s", step.description)
                continue
            allowed.append(step)
        return allowed

    def _fallback_plan(self, goal: str) -> List[TaskStep]:
        """Minimal 2-step plan when planner fails."""
        return [
            TaskStep(
                description=f"Research and gather information to address: {goal}",
                tool_used="web_search",
                requires_approval=False,
            ),
            TaskStep(
                description="Synthesize findings and deliver final answer",
                tool_used="llm_only",
                requires_approval=False,
            ),
        ]


# Singleton
planner_service = PlannerService()
